//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Assets/Scripts/InputController.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Scripts/InputController.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @InputController: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @InputController()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""InputController"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""488819ea-fa20-45bc-b799-a23be0f09b20"",
            ""actions"": [
                {
                    ""name"": ""TestLinearSimple"",
                    ""type"": ""Button"",
                    ""id"": ""37599b4e-496f-40b9-b93b-b74394862a20"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TestLinearMultiple"",
                    ""type"": ""Button"",
                    ""id"": ""d93365c1-54bc-4bdd-a2e2-71dec9845c8f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TestXOR"",
                    ""type"": ""Button"",
                    ""id"": ""5278dc74-a6cb-44ac-bb07-8a5b5faece62"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TestCross"",
                    ""type"": ""Button"",
                    ""id"": ""104c4db8-a682-4109-bb2c-970844a91ecc"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TestLinearSimple2d"",
                    ""type"": ""Button"",
                    ""id"": ""fbcd0c03-e9dc-46f7-a6ef-4ead2ef3ecb3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TestNonLinearSimple2d"",
                    ""type"": ""Button"",
                    ""id"": ""06e0a723-bf39-46db-b1dd-42185ff8df9e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TestLinearSimple3d"",
                    ""type"": ""Button"",
                    ""id"": ""2f227e5b-57b2-4270-b095-274d3994f0d1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TestLinearTrick3d"",
                    ""type"": ""Button"",
                    ""id"": ""d786f184-8d7b-4b30-a94f-6165dc3fe417"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TestNonLinearSimple3d"",
                    ""type"": ""Button"",
                    ""id"": ""8fddadf5-ec49-4e00-8d8d-9164523a632b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TestLinearSimplePMC"",
                    ""type"": ""Button"",
                    ""id"": ""1c8eb7ee-e77c-40fe-8c38-f03b6dfdc76a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TestLinearMultiplePMC"",
                    ""type"": ""Button"",
                    ""id"": ""6917e372-2f7f-49db-b084-70f9305e8d2a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TestXORPMC"",
                    ""type"": ""Button"",
                    ""id"": ""ff22c8b5-95a8-4549-84f3-5b6207b4bedc"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TestCrossPMC"",
                    ""type"": ""Button"",
                    ""id"": ""c9256df6-4c62-4145-bb1b-1066c85a49a7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TestMultiLinear3Classes"",
                    ""type"": ""Button"",
                    ""id"": ""29ea8072-a0a6-4f81-b4e6-801856a1d16b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TestMultiCross"",
                    ""type"": ""Button"",
                    ""id"": ""937f82ea-f65e-4414-b851-1d064bb50559"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TestLinearSimple2DPMC"",
                    ""type"": ""Button"",
                    ""id"": ""8e79cab8-4655-401d-8030-9ced1d47b578"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TestNonLinearSimple2DPMC"",
                    ""type"": ""Button"",
                    ""id"": ""e4037101-aab2-457e-a383-68d8b582d079"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TestLinearSimple3DPMC"",
                    ""type"": ""Button"",
                    ""id"": ""3051a3ee-60ad-42a6-9e7d-71a5b1407bc4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TestLinearTrick3DPMC"",
                    ""type"": ""Button"",
                    ""id"": ""a325fbcc-8ba1-422a-894a-9f007059ad9e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TestNonLinearSimple3DPMC"",
                    ""type"": ""Button"",
                    ""id"": ""74ad5d90-8aa7-43a1-acc7-8dc6d111c38b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ef28753a-8a47-4f78-a2e8-bc3cb8ccab3c"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TestLinearSimple"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ec6d4d71-0595-4a4b-9abc-2ad1f094e758"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TestLinearMultiple"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""18dc6884-915d-4548-a2a7-c60cfd772066"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TestXOR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f4ebd87c-c4bc-42ff-8f0b-a49cabb70667"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TestCross"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2f0f969e-d197-4b9d-83f8-e67b3c8a4506"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TestLinearSimple2d"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""21d7cd7c-ed2b-49f0-8a33-29df495dba83"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TestNonLinearSimple2d"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5bcb43d2-8646-45c9-9526-32ce2a0a0640"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TestLinearSimple3d"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b41369a6-7db6-4f81-b26d-998a45ea4149"",
                    ""path"": ""<Keyboard>/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TestLinearTrick3d"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d7ad4070-1ea1-403d-8e37-d0ca8034d57d"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TestNonLinearSimple3d"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ec5670f3-c076-4dbf-8b4c-d7e043164c6f"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TestLinearSimplePMC"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""555abb02-3dd0-4229-9df4-83c982db8313"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TestLinearMultiplePMC"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e2b41a99-d8e9-498d-9b17-f9f162348065"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TestXORPMC"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6d14e0b1-879e-418c-be84-27db8995a277"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TestCrossPMC"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1bc38c99-c21a-4c05-bf87-750f2e4a5f97"",
                    ""path"": ""<Keyboard>/n"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TestMultiLinear3Classes"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eff78d33-15bf-4810-b168-65bcf639fae2"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TestMultiCross"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1b8e3ddc-c49d-4754-bf82-71b1b607a70b"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TestLinearSimple2DPMC"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bc2b945e-844e-45aa-80e1-9ca284072bc3"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TestNonLinearSimple2DPMC"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6ebe0b50-59cd-474f-a356-a26d80a619c5"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TestLinearSimple3DPMC"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d4587ad0-69ca-4dba-a1e3-a391aed0c222"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TestLinearTrick3DPMC"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""83126e50-ca1d-42cf-8fc1-2c4addccafd3"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TestNonLinearSimple3DPMC"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_TestLinearSimple = m_Player.FindAction("TestLinearSimple", throwIfNotFound: true);
        m_Player_TestLinearMultiple = m_Player.FindAction("TestLinearMultiple", throwIfNotFound: true);
        m_Player_TestXOR = m_Player.FindAction("TestXOR", throwIfNotFound: true);
        m_Player_TestCross = m_Player.FindAction("TestCross", throwIfNotFound: true);
        m_Player_TestLinearSimple2d = m_Player.FindAction("TestLinearSimple2d", throwIfNotFound: true);
        m_Player_TestNonLinearSimple2d = m_Player.FindAction("TestNonLinearSimple2d", throwIfNotFound: true);
        m_Player_TestLinearSimple3d = m_Player.FindAction("TestLinearSimple3d", throwIfNotFound: true);
        m_Player_TestLinearTrick3d = m_Player.FindAction("TestLinearTrick3d", throwIfNotFound: true);
        m_Player_TestNonLinearSimple3d = m_Player.FindAction("TestNonLinearSimple3d", throwIfNotFound: true);
        m_Player_TestLinearSimplePMC = m_Player.FindAction("TestLinearSimplePMC", throwIfNotFound: true);
        m_Player_TestLinearMultiplePMC = m_Player.FindAction("TestLinearMultiplePMC", throwIfNotFound: true);
        m_Player_TestXORPMC = m_Player.FindAction("TestXORPMC", throwIfNotFound: true);
        m_Player_TestCrossPMC = m_Player.FindAction("TestCrossPMC", throwIfNotFound: true);
        m_Player_TestMultiLinear3Classes = m_Player.FindAction("TestMultiLinear3Classes", throwIfNotFound: true);
        m_Player_TestMultiCross = m_Player.FindAction("TestMultiCross", throwIfNotFound: true);
        m_Player_TestLinearSimple2DPMC = m_Player.FindAction("TestLinearSimple2DPMC", throwIfNotFound: true);
        m_Player_TestNonLinearSimple2DPMC = m_Player.FindAction("TestNonLinearSimple2DPMC", throwIfNotFound: true);
        m_Player_TestLinearSimple3DPMC = m_Player.FindAction("TestLinearSimple3DPMC", throwIfNotFound: true);
        m_Player_TestLinearTrick3DPMC = m_Player.FindAction("TestLinearTrick3DPMC", throwIfNotFound: true);
        m_Player_TestNonLinearSimple3DPMC = m_Player.FindAction("TestNonLinearSimple3DPMC", throwIfNotFound: true);
    }

    ~@InputController()
    {
        UnityEngine.Debug.Assert(!m_Player.enabled, "This will cause a leak and performance issues, InputController.Player.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_TestLinearSimple;
    private readonly InputAction m_Player_TestLinearMultiple;
    private readonly InputAction m_Player_TestXOR;
    private readonly InputAction m_Player_TestCross;
    private readonly InputAction m_Player_TestLinearSimple2d;
    private readonly InputAction m_Player_TestNonLinearSimple2d;
    private readonly InputAction m_Player_TestLinearSimple3d;
    private readonly InputAction m_Player_TestLinearTrick3d;
    private readonly InputAction m_Player_TestNonLinearSimple3d;
    private readonly InputAction m_Player_TestLinearSimplePMC;
    private readonly InputAction m_Player_TestLinearMultiplePMC;
    private readonly InputAction m_Player_TestXORPMC;
    private readonly InputAction m_Player_TestCrossPMC;
    private readonly InputAction m_Player_TestMultiLinear3Classes;
    private readonly InputAction m_Player_TestMultiCross;
    private readonly InputAction m_Player_TestLinearSimple2DPMC;
    private readonly InputAction m_Player_TestNonLinearSimple2DPMC;
    private readonly InputAction m_Player_TestLinearSimple3DPMC;
    private readonly InputAction m_Player_TestLinearTrick3DPMC;
    private readonly InputAction m_Player_TestNonLinearSimple3DPMC;
    /// <summary>
    /// Provides access to input actions defined in input action map "Player".
    /// </summary>
    public struct PlayerActions
    {
        private @InputController m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public PlayerActions(@InputController wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Player/TestLinearSimple".
        /// </summary>
        public InputAction @TestLinearSimple => m_Wrapper.m_Player_TestLinearSimple;
        /// <summary>
        /// Provides access to the underlying input action "Player/TestLinearMultiple".
        /// </summary>
        public InputAction @TestLinearMultiple => m_Wrapper.m_Player_TestLinearMultiple;
        /// <summary>
        /// Provides access to the underlying input action "Player/TestXOR".
        /// </summary>
        public InputAction @TestXOR => m_Wrapper.m_Player_TestXOR;
        /// <summary>
        /// Provides access to the underlying input action "Player/TestCross".
        /// </summary>
        public InputAction @TestCross => m_Wrapper.m_Player_TestCross;
        /// <summary>
        /// Provides access to the underlying input action "Player/TestLinearSimple2d".
        /// </summary>
        public InputAction @TestLinearSimple2d => m_Wrapper.m_Player_TestLinearSimple2d;
        /// <summary>
        /// Provides access to the underlying input action "Player/TestNonLinearSimple2d".
        /// </summary>
        public InputAction @TestNonLinearSimple2d => m_Wrapper.m_Player_TestNonLinearSimple2d;
        /// <summary>
        /// Provides access to the underlying input action "Player/TestLinearSimple3d".
        /// </summary>
        public InputAction @TestLinearSimple3d => m_Wrapper.m_Player_TestLinearSimple3d;
        /// <summary>
        /// Provides access to the underlying input action "Player/TestLinearTrick3d".
        /// </summary>
        public InputAction @TestLinearTrick3d => m_Wrapper.m_Player_TestLinearTrick3d;
        /// <summary>
        /// Provides access to the underlying input action "Player/TestNonLinearSimple3d".
        /// </summary>
        public InputAction @TestNonLinearSimple3d => m_Wrapper.m_Player_TestNonLinearSimple3d;
        /// <summary>
        /// Provides access to the underlying input action "Player/TestLinearSimplePMC".
        /// </summary>
        public InputAction @TestLinearSimplePMC => m_Wrapper.m_Player_TestLinearSimplePMC;
        /// <summary>
        /// Provides access to the underlying input action "Player/TestLinearMultiplePMC".
        /// </summary>
        public InputAction @TestLinearMultiplePMC => m_Wrapper.m_Player_TestLinearMultiplePMC;
        /// <summary>
        /// Provides access to the underlying input action "Player/TestXORPMC".
        /// </summary>
        public InputAction @TestXORPMC => m_Wrapper.m_Player_TestXORPMC;
        /// <summary>
        /// Provides access to the underlying input action "Player/TestCrossPMC".
        /// </summary>
        public InputAction @TestCrossPMC => m_Wrapper.m_Player_TestCrossPMC;
        /// <summary>
        /// Provides access to the underlying input action "Player/TestMultiLinear3Classes".
        /// </summary>
        public InputAction @TestMultiLinear3Classes => m_Wrapper.m_Player_TestMultiLinear3Classes;
        /// <summary>
        /// Provides access to the underlying input action "Player/TestMultiCross".
        /// </summary>
        public InputAction @TestMultiCross => m_Wrapper.m_Player_TestMultiCross;
        /// <summary>
        /// Provides access to the underlying input action "Player/TestLinearSimple2DPMC".
        /// </summary>
        public InputAction @TestLinearSimple2DPMC => m_Wrapper.m_Player_TestLinearSimple2DPMC;
        /// <summary>
        /// Provides access to the underlying input action "Player/TestNonLinearSimple2DPMC".
        /// </summary>
        public InputAction @TestNonLinearSimple2DPMC => m_Wrapper.m_Player_TestNonLinearSimple2DPMC;
        /// <summary>
        /// Provides access to the underlying input action "Player/TestLinearSimple3DPMC".
        /// </summary>
        public InputAction @TestLinearSimple3DPMC => m_Wrapper.m_Player_TestLinearSimple3DPMC;
        /// <summary>
        /// Provides access to the underlying input action "Player/TestLinearTrick3DPMC".
        /// </summary>
        public InputAction @TestLinearTrick3DPMC => m_Wrapper.m_Player_TestLinearTrick3DPMC;
        /// <summary>
        /// Provides access to the underlying input action "Player/TestNonLinearSimple3DPMC".
        /// </summary>
        public InputAction @TestNonLinearSimple3DPMC => m_Wrapper.m_Player_TestNonLinearSimple3DPMC;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="PlayerActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="PlayerActions" />
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @TestLinearSimple.started += instance.OnTestLinearSimple;
            @TestLinearSimple.performed += instance.OnTestLinearSimple;
            @TestLinearSimple.canceled += instance.OnTestLinearSimple;
            @TestLinearMultiple.started += instance.OnTestLinearMultiple;
            @TestLinearMultiple.performed += instance.OnTestLinearMultiple;
            @TestLinearMultiple.canceled += instance.OnTestLinearMultiple;
            @TestXOR.started += instance.OnTestXOR;
            @TestXOR.performed += instance.OnTestXOR;
            @TestXOR.canceled += instance.OnTestXOR;
            @TestCross.started += instance.OnTestCross;
            @TestCross.performed += instance.OnTestCross;
            @TestCross.canceled += instance.OnTestCross;
            @TestLinearSimple2d.started += instance.OnTestLinearSimple2d;
            @TestLinearSimple2d.performed += instance.OnTestLinearSimple2d;
            @TestLinearSimple2d.canceled += instance.OnTestLinearSimple2d;
            @TestNonLinearSimple2d.started += instance.OnTestNonLinearSimple2d;
            @TestNonLinearSimple2d.performed += instance.OnTestNonLinearSimple2d;
            @TestNonLinearSimple2d.canceled += instance.OnTestNonLinearSimple2d;
            @TestLinearSimple3d.started += instance.OnTestLinearSimple3d;
            @TestLinearSimple3d.performed += instance.OnTestLinearSimple3d;
            @TestLinearSimple3d.canceled += instance.OnTestLinearSimple3d;
            @TestLinearTrick3d.started += instance.OnTestLinearTrick3d;
            @TestLinearTrick3d.performed += instance.OnTestLinearTrick3d;
            @TestLinearTrick3d.canceled += instance.OnTestLinearTrick3d;
            @TestNonLinearSimple3d.started += instance.OnTestNonLinearSimple3d;
            @TestNonLinearSimple3d.performed += instance.OnTestNonLinearSimple3d;
            @TestNonLinearSimple3d.canceled += instance.OnTestNonLinearSimple3d;
            @TestLinearSimplePMC.started += instance.OnTestLinearSimplePMC;
            @TestLinearSimplePMC.performed += instance.OnTestLinearSimplePMC;
            @TestLinearSimplePMC.canceled += instance.OnTestLinearSimplePMC;
            @TestLinearMultiplePMC.started += instance.OnTestLinearMultiplePMC;
            @TestLinearMultiplePMC.performed += instance.OnTestLinearMultiplePMC;
            @TestLinearMultiplePMC.canceled += instance.OnTestLinearMultiplePMC;
            @TestXORPMC.started += instance.OnTestXORPMC;
            @TestXORPMC.performed += instance.OnTestXORPMC;
            @TestXORPMC.canceled += instance.OnTestXORPMC;
            @TestCrossPMC.started += instance.OnTestCrossPMC;
            @TestCrossPMC.performed += instance.OnTestCrossPMC;
            @TestCrossPMC.canceled += instance.OnTestCrossPMC;
            @TestMultiLinear3Classes.started += instance.OnTestMultiLinear3Classes;
            @TestMultiLinear3Classes.performed += instance.OnTestMultiLinear3Classes;
            @TestMultiLinear3Classes.canceled += instance.OnTestMultiLinear3Classes;
            @TestMultiCross.started += instance.OnTestMultiCross;
            @TestMultiCross.performed += instance.OnTestMultiCross;
            @TestMultiCross.canceled += instance.OnTestMultiCross;
            @TestLinearSimple2DPMC.started += instance.OnTestLinearSimple2DPMC;
            @TestLinearSimple2DPMC.performed += instance.OnTestLinearSimple2DPMC;
            @TestLinearSimple2DPMC.canceled += instance.OnTestLinearSimple2DPMC;
            @TestNonLinearSimple2DPMC.started += instance.OnTestNonLinearSimple2DPMC;
            @TestNonLinearSimple2DPMC.performed += instance.OnTestNonLinearSimple2DPMC;
            @TestNonLinearSimple2DPMC.canceled += instance.OnTestNonLinearSimple2DPMC;
            @TestLinearSimple3DPMC.started += instance.OnTestLinearSimple3DPMC;
            @TestLinearSimple3DPMC.performed += instance.OnTestLinearSimple3DPMC;
            @TestLinearSimple3DPMC.canceled += instance.OnTestLinearSimple3DPMC;
            @TestLinearTrick3DPMC.started += instance.OnTestLinearTrick3DPMC;
            @TestLinearTrick3DPMC.performed += instance.OnTestLinearTrick3DPMC;
            @TestLinearTrick3DPMC.canceled += instance.OnTestLinearTrick3DPMC;
            @TestNonLinearSimple3DPMC.started += instance.OnTestNonLinearSimple3DPMC;
            @TestNonLinearSimple3DPMC.performed += instance.OnTestNonLinearSimple3DPMC;
            @TestNonLinearSimple3DPMC.canceled += instance.OnTestNonLinearSimple3DPMC;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="PlayerActions" />
        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @TestLinearSimple.started -= instance.OnTestLinearSimple;
            @TestLinearSimple.performed -= instance.OnTestLinearSimple;
            @TestLinearSimple.canceled -= instance.OnTestLinearSimple;
            @TestLinearMultiple.started -= instance.OnTestLinearMultiple;
            @TestLinearMultiple.performed -= instance.OnTestLinearMultiple;
            @TestLinearMultiple.canceled -= instance.OnTestLinearMultiple;
            @TestXOR.started -= instance.OnTestXOR;
            @TestXOR.performed -= instance.OnTestXOR;
            @TestXOR.canceled -= instance.OnTestXOR;
            @TestCross.started -= instance.OnTestCross;
            @TestCross.performed -= instance.OnTestCross;
            @TestCross.canceled -= instance.OnTestCross;
            @TestLinearSimple2d.started -= instance.OnTestLinearSimple2d;
            @TestLinearSimple2d.performed -= instance.OnTestLinearSimple2d;
            @TestLinearSimple2d.canceled -= instance.OnTestLinearSimple2d;
            @TestNonLinearSimple2d.started -= instance.OnTestNonLinearSimple2d;
            @TestNonLinearSimple2d.performed -= instance.OnTestNonLinearSimple2d;
            @TestNonLinearSimple2d.canceled -= instance.OnTestNonLinearSimple2d;
            @TestLinearSimple3d.started -= instance.OnTestLinearSimple3d;
            @TestLinearSimple3d.performed -= instance.OnTestLinearSimple3d;
            @TestLinearSimple3d.canceled -= instance.OnTestLinearSimple3d;
            @TestLinearTrick3d.started -= instance.OnTestLinearTrick3d;
            @TestLinearTrick3d.performed -= instance.OnTestLinearTrick3d;
            @TestLinearTrick3d.canceled -= instance.OnTestLinearTrick3d;
            @TestNonLinearSimple3d.started -= instance.OnTestNonLinearSimple3d;
            @TestNonLinearSimple3d.performed -= instance.OnTestNonLinearSimple3d;
            @TestNonLinearSimple3d.canceled -= instance.OnTestNonLinearSimple3d;
            @TestLinearSimplePMC.started -= instance.OnTestLinearSimplePMC;
            @TestLinearSimplePMC.performed -= instance.OnTestLinearSimplePMC;
            @TestLinearSimplePMC.canceled -= instance.OnTestLinearSimplePMC;
            @TestLinearMultiplePMC.started -= instance.OnTestLinearMultiplePMC;
            @TestLinearMultiplePMC.performed -= instance.OnTestLinearMultiplePMC;
            @TestLinearMultiplePMC.canceled -= instance.OnTestLinearMultiplePMC;
            @TestXORPMC.started -= instance.OnTestXORPMC;
            @TestXORPMC.performed -= instance.OnTestXORPMC;
            @TestXORPMC.canceled -= instance.OnTestXORPMC;
            @TestCrossPMC.started -= instance.OnTestCrossPMC;
            @TestCrossPMC.performed -= instance.OnTestCrossPMC;
            @TestCrossPMC.canceled -= instance.OnTestCrossPMC;
            @TestMultiLinear3Classes.started -= instance.OnTestMultiLinear3Classes;
            @TestMultiLinear3Classes.performed -= instance.OnTestMultiLinear3Classes;
            @TestMultiLinear3Classes.canceled -= instance.OnTestMultiLinear3Classes;
            @TestMultiCross.started -= instance.OnTestMultiCross;
            @TestMultiCross.performed -= instance.OnTestMultiCross;
            @TestMultiCross.canceled -= instance.OnTestMultiCross;
            @TestLinearSimple2DPMC.started -= instance.OnTestLinearSimple2DPMC;
            @TestLinearSimple2DPMC.performed -= instance.OnTestLinearSimple2DPMC;
            @TestLinearSimple2DPMC.canceled -= instance.OnTestLinearSimple2DPMC;
            @TestNonLinearSimple2DPMC.started -= instance.OnTestNonLinearSimple2DPMC;
            @TestNonLinearSimple2DPMC.performed -= instance.OnTestNonLinearSimple2DPMC;
            @TestNonLinearSimple2DPMC.canceled -= instance.OnTestNonLinearSimple2DPMC;
            @TestLinearSimple3DPMC.started -= instance.OnTestLinearSimple3DPMC;
            @TestLinearSimple3DPMC.performed -= instance.OnTestLinearSimple3DPMC;
            @TestLinearSimple3DPMC.canceled -= instance.OnTestLinearSimple3DPMC;
            @TestLinearTrick3DPMC.started -= instance.OnTestLinearTrick3DPMC;
            @TestLinearTrick3DPMC.performed -= instance.OnTestLinearTrick3DPMC;
            @TestLinearTrick3DPMC.canceled -= instance.OnTestLinearTrick3DPMC;
            @TestNonLinearSimple3DPMC.started -= instance.OnTestNonLinearSimple3DPMC;
            @TestNonLinearSimple3DPMC.performed -= instance.OnTestNonLinearSimple3DPMC;
            @TestNonLinearSimple3DPMC.canceled -= instance.OnTestNonLinearSimple3DPMC;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PlayerActions.UnregisterCallbacks(IPlayerActions)" />.
        /// </summary>
        /// <seealso cref="PlayerActions.UnregisterCallbacks(IPlayerActions)" />
        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="PlayerActions.AddCallbacks(IPlayerActions)" />
        /// <seealso cref="PlayerActions.RemoveCallbacks(IPlayerActions)" />
        /// <seealso cref="PlayerActions.UnregisterCallbacks(IPlayerActions)" />
        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="PlayerActions" /> instance referencing this action map.
    /// </summary>
    public PlayerActions @Player => new PlayerActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Player" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="PlayerActions.AddCallbacks(IPlayerActions)" />
    /// <seealso cref="PlayerActions.RemoveCallbacks(IPlayerActions)" />
    public interface IPlayerActions
    {
        /// <summary>
        /// Method invoked when associated input action "TestLinearSimple" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTestLinearSimple(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TestLinearMultiple" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTestLinearMultiple(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TestXOR" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTestXOR(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TestCross" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTestCross(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TestLinearSimple2d" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTestLinearSimple2d(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TestNonLinearSimple2d" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTestNonLinearSimple2d(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TestLinearSimple3d" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTestLinearSimple3d(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TestLinearTrick3d" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTestLinearTrick3d(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TestNonLinearSimple3d" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTestNonLinearSimple3d(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TestLinearSimplePMC" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTestLinearSimplePMC(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TestLinearMultiplePMC" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTestLinearMultiplePMC(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TestXORPMC" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTestXORPMC(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TestCrossPMC" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTestCrossPMC(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TestMultiLinear3Classes" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTestMultiLinear3Classes(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TestMultiCross" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTestMultiCross(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TestLinearSimple2DPMC" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTestLinearSimple2DPMC(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TestNonLinearSimple2DPMC" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTestNonLinearSimple2DPMC(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TestLinearSimple3DPMC" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTestLinearSimple3DPMC(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TestLinearTrick3DPMC" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTestLinearTrick3DPMC(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TestNonLinearSimple3DPMC" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTestNonLinearSimple3DPMC(InputAction.CallbackContext context);
    }
}
