//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Assets/Scripts/InputController.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Scripts/InputController.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @InputController: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @InputController()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""InputController"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""488819ea-fa20-45bc-b799-a23be0f09b20"",
            ""actions"": [
                {
                    ""name"": ""TestLinearSimple"",
                    ""type"": ""Button"",
                    ""id"": ""37599b4e-496f-40b9-b93b-b74394862a20"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TestLinearMultiple"",
                    ""type"": ""Button"",
                    ""id"": ""d93365c1-54bc-4bdd-a2e2-71dec9845c8f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TestXOR"",
                    ""type"": ""Button"",
                    ""id"": ""5278dc74-a6cb-44ac-bb07-8a5b5faece62"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TestCross"",
                    ""type"": ""Button"",
                    ""id"": ""104c4db8-a682-4109-bb2c-970844a91ecc"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TestLinearSimple2d"",
                    ""type"": ""Button"",
                    ""id"": ""fbcd0c03-e9dc-46f7-a6ef-4ead2ef3ecb3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TestNonLinearSimple2d"",
                    ""type"": ""Button"",
                    ""id"": ""06e0a723-bf39-46db-b1dd-42185ff8df9e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TestLinearSimple3d"",
                    ""type"": ""Button"",
                    ""id"": ""2f227e5b-57b2-4270-b095-274d3994f0d1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TestLinearTrick3d"",
                    ""type"": ""Button"",
                    ""id"": ""d786f184-8d7b-4b30-a94f-6165dc3fe417"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TestNonLinearSimple3d"",
                    ""type"": ""Button"",
                    ""id"": ""8fddadf5-ec49-4e00-8d8d-9164523a632b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TestNonLinearSimple2dC"",
                    ""type"": ""Button"",
                    ""id"": ""1c8eb7ee-e77c-40fe-8c38-f03b6dfdc76a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TestNonLinearSimple2dR"",
                    ""type"": ""Button"",
                    ""id"": ""b7d2653b-8116-49ad-9696-8c4429c3435c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TestXORC"",
                    ""type"": ""Button"",
                    ""id"": ""f1f07e82-1739-4ca2-b987-84db244b4359"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TestXORR"",
                    ""type"": ""Button"",
                    ""id"": ""f1bf21d4-586b-4328-81f5-c71c7129c536"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ef28753a-8a47-4f78-a2e8-bc3cb8ccab3c"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TestLinearSimple"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ec6d4d71-0595-4a4b-9abc-2ad1f094e758"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TestLinearMultiple"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""18dc6884-915d-4548-a2a7-c60cfd772066"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TestXOR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f4ebd87c-c4bc-42ff-8f0b-a49cabb70667"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TestCross"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2f0f969e-d197-4b9d-83f8-e67b3c8a4506"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TestLinearSimple2d"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""21d7cd7c-ed2b-49f0-8a33-29df495dba83"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TestNonLinearSimple2d"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5bcb43d2-8646-45c9-9526-32ce2a0a0640"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TestLinearSimple3d"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b41369a6-7db6-4f81-b26d-998a45ea4149"",
                    ""path"": ""<Keyboard>/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TestLinearTrick3d"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d7ad4070-1ea1-403d-8e37-d0ca8034d57d"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TestNonLinearSimple3d"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ec5670f3-c076-4dbf-8b4c-d7e043164c6f"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TestNonLinearSimple2dC"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5f672b8c-4673-4981-b4ae-7d5dae5c4bd3"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TestNonLinearSimple2dR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2d5e32ae-ff8c-4fdc-bbac-1599605b7757"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TestXORC"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4d2d427d-5e10-43b4-9f80-22ea37afd311"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TestXORR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_TestLinearSimple = m_Player.FindAction("TestLinearSimple", throwIfNotFound: true);
        m_Player_TestLinearMultiple = m_Player.FindAction("TestLinearMultiple", throwIfNotFound: true);
        m_Player_TestXOR = m_Player.FindAction("TestXOR", throwIfNotFound: true);
        m_Player_TestCross = m_Player.FindAction("TestCross", throwIfNotFound: true);
        m_Player_TestLinearSimple2d = m_Player.FindAction("TestLinearSimple2d", throwIfNotFound: true);
        m_Player_TestNonLinearSimple2d = m_Player.FindAction("TestNonLinearSimple2d", throwIfNotFound: true);
        m_Player_TestLinearSimple3d = m_Player.FindAction("TestLinearSimple3d", throwIfNotFound: true);
        m_Player_TestLinearTrick3d = m_Player.FindAction("TestLinearTrick3d", throwIfNotFound: true);
        m_Player_TestNonLinearSimple3d = m_Player.FindAction("TestNonLinearSimple3d", throwIfNotFound: true);
        m_Player_TestNonLinearSimple2dC = m_Player.FindAction("TestNonLinearSimple2dC", throwIfNotFound: true);
        m_Player_TestNonLinearSimple2dR = m_Player.FindAction("TestNonLinearSimple2dR", throwIfNotFound: true);
        m_Player_TestXORC = m_Player.FindAction("TestXORC", throwIfNotFound: true);
        m_Player_TestXORR = m_Player.FindAction("TestXORR", throwIfNotFound: true);
    }

    ~@InputController()
    {
        UnityEngine.Debug.Assert(!m_Player.enabled, "This will cause a leak and performance issues, InputController.Player.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_TestLinearSimple;
    private readonly InputAction m_Player_TestLinearMultiple;
    private readonly InputAction m_Player_TestXOR;
    private readonly InputAction m_Player_TestCross;
    private readonly InputAction m_Player_TestLinearSimple2d;
    private readonly InputAction m_Player_TestNonLinearSimple2d;
    private readonly InputAction m_Player_TestLinearSimple3d;
    private readonly InputAction m_Player_TestLinearTrick3d;
    private readonly InputAction m_Player_TestNonLinearSimple3d;
    private readonly InputAction m_Player_TestNonLinearSimple2dC;
    private readonly InputAction m_Player_TestNonLinearSimple2dR;
    private readonly InputAction m_Player_TestXORC;
    private readonly InputAction m_Player_TestXORR;
    /// <summary>
    /// Provides access to input actions defined in input action map "Player".
    /// </summary>
    public struct PlayerActions
    {
        private @InputController m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public PlayerActions(@InputController wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Player/TestLinearSimple".
        /// </summary>
        public InputAction @TestLinearSimple => m_Wrapper.m_Player_TestLinearSimple;
        /// <summary>
        /// Provides access to the underlying input action "Player/TestLinearMultiple".
        /// </summary>
        public InputAction @TestLinearMultiple => m_Wrapper.m_Player_TestLinearMultiple;
        /// <summary>
        /// Provides access to the underlying input action "Player/TestXOR".
        /// </summary>
        public InputAction @TestXOR => m_Wrapper.m_Player_TestXOR;
        /// <summary>
        /// Provides access to the underlying input action "Player/TestCross".
        /// </summary>
        public InputAction @TestCross => m_Wrapper.m_Player_TestCross;
        /// <summary>
        /// Provides access to the underlying input action "Player/TestLinearSimple2d".
        /// </summary>
        public InputAction @TestLinearSimple2d => m_Wrapper.m_Player_TestLinearSimple2d;
        /// <summary>
        /// Provides access to the underlying input action "Player/TestNonLinearSimple2d".
        /// </summary>
        public InputAction @TestNonLinearSimple2d => m_Wrapper.m_Player_TestNonLinearSimple2d;
        /// <summary>
        /// Provides access to the underlying input action "Player/TestLinearSimple3d".
        /// </summary>
        public InputAction @TestLinearSimple3d => m_Wrapper.m_Player_TestLinearSimple3d;
        /// <summary>
        /// Provides access to the underlying input action "Player/TestLinearTrick3d".
        /// </summary>
        public InputAction @TestLinearTrick3d => m_Wrapper.m_Player_TestLinearTrick3d;
        /// <summary>
        /// Provides access to the underlying input action "Player/TestNonLinearSimple3d".
        /// </summary>
        public InputAction @TestNonLinearSimple3d => m_Wrapper.m_Player_TestNonLinearSimple3d;
        /// <summary>
        /// Provides access to the underlying input action "Player/TestNonLinearSimple2dC".
        /// </summary>
        public InputAction @TestNonLinearSimple2dC => m_Wrapper.m_Player_TestNonLinearSimple2dC;
        /// <summary>
        /// Provides access to the underlying input action "Player/TestNonLinearSimple2dR".
        /// </summary>
        public InputAction @TestNonLinearSimple2dR => m_Wrapper.m_Player_TestNonLinearSimple2dR;
        /// <summary>
        /// Provides access to the underlying input action "Player/TestXORC".
        /// </summary>
        public InputAction @TestXORC => m_Wrapper.m_Player_TestXORC;
        /// <summary>
        /// Provides access to the underlying input action "Player/TestXORR".
        /// </summary>
        public InputAction @TestXORR => m_Wrapper.m_Player_TestXORR;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="PlayerActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="PlayerActions" />
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @TestLinearSimple.started += instance.OnTestLinearSimple;
            @TestLinearSimple.performed += instance.OnTestLinearSimple;
            @TestLinearSimple.canceled += instance.OnTestLinearSimple;
            @TestLinearMultiple.started += instance.OnTestLinearMultiple;
            @TestLinearMultiple.performed += instance.OnTestLinearMultiple;
            @TestLinearMultiple.canceled += instance.OnTestLinearMultiple;
            @TestXOR.started += instance.OnTestXOR;
            @TestXOR.performed += instance.OnTestXOR;
            @TestXOR.canceled += instance.OnTestXOR;
            @TestCross.started += instance.OnTestCross;
            @TestCross.performed += instance.OnTestCross;
            @TestCross.canceled += instance.OnTestCross;
            @TestLinearSimple2d.started += instance.OnTestLinearSimple2d;
            @TestLinearSimple2d.performed += instance.OnTestLinearSimple2d;
            @TestLinearSimple2d.canceled += instance.OnTestLinearSimple2d;
            @TestNonLinearSimple2d.started += instance.OnTestNonLinearSimple2d;
            @TestNonLinearSimple2d.performed += instance.OnTestNonLinearSimple2d;
            @TestNonLinearSimple2d.canceled += instance.OnTestNonLinearSimple2d;
            @TestLinearSimple3d.started += instance.OnTestLinearSimple3d;
            @TestLinearSimple3d.performed += instance.OnTestLinearSimple3d;
            @TestLinearSimple3d.canceled += instance.OnTestLinearSimple3d;
            @TestLinearTrick3d.started += instance.OnTestLinearTrick3d;
            @TestLinearTrick3d.performed += instance.OnTestLinearTrick3d;
            @TestLinearTrick3d.canceled += instance.OnTestLinearTrick3d;
            @TestNonLinearSimple3d.started += instance.OnTestNonLinearSimple3d;
            @TestNonLinearSimple3d.performed += instance.OnTestNonLinearSimple3d;
            @TestNonLinearSimple3d.canceled += instance.OnTestNonLinearSimple3d;
            @TestNonLinearSimple2dC.started += instance.OnTestNonLinearSimple2dC;
            @TestNonLinearSimple2dC.performed += instance.OnTestNonLinearSimple2dC;
            @TestNonLinearSimple2dC.canceled += instance.OnTestNonLinearSimple2dC;
            @TestNonLinearSimple2dR.started += instance.OnTestNonLinearSimple2dR;
            @TestNonLinearSimple2dR.performed += instance.OnTestNonLinearSimple2dR;
            @TestNonLinearSimple2dR.canceled += instance.OnTestNonLinearSimple2dR;
            @TestXORC.started += instance.OnTestXORC;
            @TestXORC.performed += instance.OnTestXORC;
            @TestXORC.canceled += instance.OnTestXORC;
            @TestXORR.started += instance.OnTestXORR;
            @TestXORR.performed += instance.OnTestXORR;
            @TestXORR.canceled += instance.OnTestXORR;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="PlayerActions" />
        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @TestLinearSimple.started -= instance.OnTestLinearSimple;
            @TestLinearSimple.performed -= instance.OnTestLinearSimple;
            @TestLinearSimple.canceled -= instance.OnTestLinearSimple;
            @TestLinearMultiple.started -= instance.OnTestLinearMultiple;
            @TestLinearMultiple.performed -= instance.OnTestLinearMultiple;
            @TestLinearMultiple.canceled -= instance.OnTestLinearMultiple;
            @TestXOR.started -= instance.OnTestXOR;
            @TestXOR.performed -= instance.OnTestXOR;
            @TestXOR.canceled -= instance.OnTestXOR;
            @TestCross.started -= instance.OnTestCross;
            @TestCross.performed -= instance.OnTestCross;
            @TestCross.canceled -= instance.OnTestCross;
            @TestLinearSimple2d.started -= instance.OnTestLinearSimple2d;
            @TestLinearSimple2d.performed -= instance.OnTestLinearSimple2d;
            @TestLinearSimple2d.canceled -= instance.OnTestLinearSimple2d;
            @TestNonLinearSimple2d.started -= instance.OnTestNonLinearSimple2d;
            @TestNonLinearSimple2d.performed -= instance.OnTestNonLinearSimple2d;
            @TestNonLinearSimple2d.canceled -= instance.OnTestNonLinearSimple2d;
            @TestLinearSimple3d.started -= instance.OnTestLinearSimple3d;
            @TestLinearSimple3d.performed -= instance.OnTestLinearSimple3d;
            @TestLinearSimple3d.canceled -= instance.OnTestLinearSimple3d;
            @TestLinearTrick3d.started -= instance.OnTestLinearTrick3d;
            @TestLinearTrick3d.performed -= instance.OnTestLinearTrick3d;
            @TestLinearTrick3d.canceled -= instance.OnTestLinearTrick3d;
            @TestNonLinearSimple3d.started -= instance.OnTestNonLinearSimple3d;
            @TestNonLinearSimple3d.performed -= instance.OnTestNonLinearSimple3d;
            @TestNonLinearSimple3d.canceled -= instance.OnTestNonLinearSimple3d;
            @TestNonLinearSimple2dC.started -= instance.OnTestNonLinearSimple2dC;
            @TestNonLinearSimple2dC.performed -= instance.OnTestNonLinearSimple2dC;
            @TestNonLinearSimple2dC.canceled -= instance.OnTestNonLinearSimple2dC;
            @TestNonLinearSimple2dR.started -= instance.OnTestNonLinearSimple2dR;
            @TestNonLinearSimple2dR.performed -= instance.OnTestNonLinearSimple2dR;
            @TestNonLinearSimple2dR.canceled -= instance.OnTestNonLinearSimple2dR;
            @TestXORC.started -= instance.OnTestXORC;
            @TestXORC.performed -= instance.OnTestXORC;
            @TestXORC.canceled -= instance.OnTestXORC;
            @TestXORR.started -= instance.OnTestXORR;
            @TestXORR.performed -= instance.OnTestXORR;
            @TestXORR.canceled -= instance.OnTestXORR;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PlayerActions.UnregisterCallbacks(IPlayerActions)" />.
        /// </summary>
        /// <seealso cref="PlayerActions.UnregisterCallbacks(IPlayerActions)" />
        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="PlayerActions.AddCallbacks(IPlayerActions)" />
        /// <seealso cref="PlayerActions.RemoveCallbacks(IPlayerActions)" />
        /// <seealso cref="PlayerActions.UnregisterCallbacks(IPlayerActions)" />
        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="PlayerActions" /> instance referencing this action map.
    /// </summary>
    public PlayerActions @Player => new PlayerActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Player" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="PlayerActions.AddCallbacks(IPlayerActions)" />
    /// <seealso cref="PlayerActions.RemoveCallbacks(IPlayerActions)" />
    public interface IPlayerActions
    {
        /// <summary>
        /// Method invoked when associated input action "TestLinearSimple" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTestLinearSimple(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TestLinearMultiple" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTestLinearMultiple(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TestXOR" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTestXOR(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TestCross" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTestCross(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TestLinearSimple2d" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTestLinearSimple2d(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TestNonLinearSimple2d" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTestNonLinearSimple2d(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TestLinearSimple3d" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTestLinearSimple3d(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TestLinearTrick3d" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTestLinearTrick3d(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TestNonLinearSimple3d" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTestNonLinearSimple3d(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TestNonLinearSimple2dC" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTestNonLinearSimple2dC(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TestNonLinearSimple2dR" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTestNonLinearSimple2dR(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TestXORC" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTestXORC(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TestXORR" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTestXORR(InputAction.CallbackContext context);
    }
}
